server:
  port: 5555

spring:
  application:
    name: api-gateway

  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: auth-service-app
          uri: lb://AUTHSERVICEAPP
          predicates:
            - Path=/auth/**
          filters:
            # Corrected RewritePath syntax
            - name: RewritePath
              args:
                regexp: "/auth/(?<segment>.*)"
                replacement: "/${segment}"
            # CircuitBreaker filter
            - name: CircuitBreaker
              args:
                name: authServiceCircuit
                fallbackUri: forward:/fallback/auth

resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuit:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
