server:
  port: 5555

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ================= AUTH SERVICE =================
        - id: auth-service
          uri: lb://AUTHSERVICEAPP
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
            - CircuitBreaker
              name: authServiceCircuit
              fallbackUri: forward:/fallback/auth

        # ================= BOOKING SERVICE =================
        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/booking/**

        # ================= PROPERTY SERVICE =================
        - id: property-service
          uri: lb://PROPERTYSERVICE
          predicates:
            - Path=/property/**

        # ================= ADMIN / MICRO SERVICE =================
        - id: admin-service
          uri: lb://ADMINSERVICE
          predicates:
            - Path=/api/v1/admin/**

# ================= RESILIENCE4J =================
resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuit:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

# ================= ACTUATOR =================
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

# ================= LOGGING =================
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
