spring:
  application:
    name: authserviceapp

  datasource:
    url: jdbc:mysql://database-2.cjgeiy4eefq2.ap-south-1.rds.amazonaws.com:3306/hmsauthdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: auth_user
    password: Auth@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 9094
