spring:
  application:
    name: authserviceapp

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true
