spring:
  application:
    name: bookingservice

  datasource:
    url: ${BOOKING_DB_URL}
    username: ${BOOKING_DB_USERNAME}
    password: ${BOOKING_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1125

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true


resilience4j:
  circuitbreaker:
    instances:
      propertyService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      propertyService:
        maxAttempts: 3
        waitDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
