spring:
  application:
    name: bookingservice

  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb1
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
