spring:
  application:
    name: propertyservice
  datasource:
    url: ${PROPERTY_DB_URL}
    username: ${PROPERTY_DB_USERNAME}
    password: ${PROPERTY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 0
    timeout: 60000
    client-type: lettuce
  cache:
    type: redis
  # ------------------ MULTIPART (commented out for now) ------------------
  # servlet:
  #   multipart:
  #     enabled: true
  #     max-file-size: 10MB
  #     max-request-size: 20MB
  # -----------------------------------------------------------------------
  # ------------------ KAFKA (commented out for now) ------------------
  # kafka:
  #   bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  #   consumer:
  #     group-id: notification-group
  #     auto-offset-reset: earliest
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  #     properties:
  #       spring.json.trusted.packages: '*'
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #     properties:
  #       spring.json.add.type.headers: false
  # -----------------------------------------------------------------------
  main:
    allow-circular-references: true

# ------------------ AWS S3 (commented out for now) ------------------
# cloud:
#   aws:
#     region:
#       static: ap-south-1
#     credentials:
#       access-key: ${AWS_ACCESS_KEY}
#       secret-key: ${AWS_SECRET_KEY}
#     s3:
#       bucket-name: my-hotel-images-2025
# --------------------------------------------------------------------

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true
